"""Generate Test STL Files

Creates simple test models for import testing.
"""

from pathlib import Path

import numpy as np


def write_stl_binary(filepath: Path, vertices: np.ndarray, faces: np.ndarray):
    """Write binary STL file."""
    import struct
    
    with open(filepath, 'wb') as f:
        # Header (80 bytes)
        header = b'Binary STL generated by AdaptiveCAD' + b' ' * 44
        f.write(header)
        
        # Number of triangles
        f.write(struct.pack('<I', len(faces)))
        
        # Write each triangle
        for face in faces:
            v0 = vertices[face[0]]
            v1 = vertices[face[1]]
            v2 = vertices[face[2]]
            
            # Compute normal
            edge1 = v1 - v0
            edge2 = v2 - v0
            normal = np.cross(edge1, edge2)
            norm = np.linalg.norm(normal)
            if norm > 1e-9:
                normal = normal / norm
            else:
                normal = np.array([0, 0, 1])
            
            # Write normal
            f.write(struct.pack('<fff', *normal))
            
            # Write vertices
            f.write(struct.pack('<fff', *v0))
            f.write(struct.pack('<fff', *v1))
            f.write(struct.pack('<fff', *v2))
            
            # Attribute byte count (unused)
            f.write(struct.pack('<H', 0))


def generate_cube_stl(size: float = 1.0) -> tuple:
    """Generate a simple cube."""
    s = size / 2
    
    vertices = np.array([
        [-s, -s, -s], [s, -s, -s], [s, s, -s], [-s, s, -s],  # Bottom
        [-s, -s, s], [s, -s, s], [s, s, s], [-s, s, s],  # Top
    ], dtype=np.float32)
    
    faces = np.array([
        # Bottom
        [0, 1, 2], [0, 2, 3],
        # Top
        [4, 6, 5], [4, 7, 6],
        # Front
        [0, 5, 1], [0, 4, 5],
        # Back
        [2, 7, 3], [2, 6, 7],
        # Left
        [0, 3, 7], [0, 7, 4],
        # Right
        [1, 6, 2], [1, 5, 6],
    ], dtype=np.int32)
    
    return vertices, faces


def generate_cylinder_stl(radius: float = 0.5, height: float = 2.0, segments: int = 32) -> tuple:
    """Generate a cylinder."""
    vertices = []
    faces = []
    
    # Bottom center
    vertices.append([0, 0, 0])
    # Top center
    vertices.append([0, 0, height])
    
    # Bottom ring
    for i in range(segments):
        angle = 2 * np.pi * i / segments
        x = radius * np.cos(angle)
        y = radius * np.sin(angle)
        vertices.append([x, y, 0])
    
    # Top ring
    for i in range(segments):
        angle = 2 * np.pi * i / segments
        x = radius * np.cos(angle)
        y = radius * np.sin(angle)
        vertices.append([x, y, height])
    
    vertices = np.array(vertices, dtype=np.float32)
    
    # Bottom cap
    for i in range(segments):
        next_i = (i + 1) % segments
        faces.append([0, i + 2, next_i + 2])
    
    # Top cap
    for i in range(segments):
        next_i = (i + 1) % segments
        faces.append([1, next_i + 2 + segments, i + 2 + segments])
    
    # Side faces
    for i in range(segments):
        next_i = (i + 1) % segments
        bottom_i = i + 2
        bottom_next = next_i + 2
        top_i = i + 2 + segments
        top_next = next_i + 2 + segments
        
        faces.append([bottom_i, top_i, bottom_next])
        faces.append([bottom_next, top_i, top_next])
    
    faces = np.array(faces, dtype=np.int32)
    
    return vertices, faces


def generate_simple_boat_stl() -> tuple:
    """Generate a simplified boat shape (mini-benchy!)."""
    vertices = []
    faces = []
    
    # Hull bottom (flat)
    hull_bottom = [
        [0, 0, 0],
        [2, 0, 0],
        [2, 1, 0],
        [0, 1, 0],
    ]
    
    # Hull top (sides slope in)
    hull_top = [
        [0.3, 0.2, 0.5],
        [1.7, 0.2, 0.5],
        [1.7, 0.8, 0.5],
        [0.3, 0.8, 0.5],
    ]
    
    # Deck
    deck = [
        [0.4, 0.3, 0.5],
        [1.6, 0.3, 0.5],
        [1.6, 0.7, 0.5],
        [0.4, 0.7, 0.5],
    ]
    
    # Cabin
    cabin_base = [
        [0.6, 0.35, 0.5],
        [1.2, 0.35, 0.5],
        [1.2, 0.65, 0.5],
        [0.6, 0.65, 0.5],
    ]
    
    cabin_top = [
        [0.65, 0.4, 0.9],
        [1.15, 0.4, 0.9],
        [1.15, 0.6, 0.9],
        [0.65, 0.6, 0.9],
    ]
    
    # Smokestack
    smokestack_base = [
        [0.85, 0.45, 0.9],
        [0.95, 0.45, 0.9],
        [0.95, 0.55, 0.9],
        [0.85, 0.55, 0.9],
    ]
    
    smokestack_top = [
        [0.85, 0.45, 1.2],
        [0.95, 0.45, 1.2],
        [0.95, 0.55, 1.2],
        [0.85, 0.55, 1.2],
    ]
    
    # Combine all vertices
    all_parts = [hull_bottom, hull_top, deck, cabin_base, cabin_top, smokestack_base, smokestack_top]
    
    for part in all_parts:
        vertices.extend(part)
    
    vertices = np.array(vertices, dtype=np.float32)
    
    # Generate faces (quads split into triangles)
    def add_quad_faces(start_idx, reverse=False):
        if reverse:
            faces.append([start_idx, start_idx + 2, start_idx + 1])
            faces.append([start_idx, start_idx + 3, start_idx + 2])
        else:
            faces.append([start_idx, start_idx + 1, start_idx + 2])
            faces.append([start_idx, start_idx + 2, start_idx + 3])
    
    def connect_layers(bottom_start, top_start):
        """Connect two rectangular layers."""
        for i in range(4):
            next_i = (i + 1) % 4
            b0 = bottom_start + i
            b1 = bottom_start + next_i
            t0 = top_start + i
            t1 = top_start + next_i
            faces.append([b0, t0, b1])
            faces.append([b1, t0, t1])
    
    # Hull
    add_quad_faces(0, reverse=True)  # Bottom
    add_quad_faces(4)  # Top (deck level)
    connect_layers(0, 4)  # Sides
    
    # Cabin
    connect_layers(12, 16)  # Sides
    add_quad_faces(16)  # Top
    
    # Smokestack
    connect_layers(20, 24)  # Sides
    add_quad_faces(24)  # Top
    
    faces = np.array(faces, dtype=np.int32)
    
    # Center and scale
    center = np.mean(vertices, axis=0)
    vertices -= center
    vertices *= 15  # Scale up to ~30mm
    
    return vertices, faces


if __name__ == "__main__":
    """Generate test models."""
    output_dir = Path(__file__).parent.parent.parent / "test_models"
    output_dir.mkdir(exist_ok=True)
    
    # Cube
    v, f = generate_cube_stl(10.0)
    write_stl_binary(output_dir / "test_cube.stl", v, f)
    print("Generated test_cube.stl")
    
    # Cylinder
    v, f = generate_cylinder_stl(5.0, 15.0, 48)
    write_stl_binary(output_dir / "test_cylinder.stl", v, f)
    print("Generated test_cylinder.stl")
    
    # Simple boat
    v, f = generate_simple_boat_stl()
    write_stl_binary(output_dir / "simple_boat.stl", v, f)
    print("Generated simple_boat.stl (mini-benchy!)")
    
    print(f"\\nTest models saved to: {output_dir}")
    print("\\nImport them in AdaptiveCAD: File > Import > Import STL/OBJ as SDF")
